[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29.0"
engine = { path = "../engine" }
tui-textarea = "0.7.0"
arboard = { version = "3.4.1", default-features = false }
rand = "0.9.0"
